### ISSUE TITLE
Assistance using with Django

### ISSUE THREAD

**Issue by akrf** [bitly/google_auth_proxy#47]
I'm trying to use google auth proxy with a django project but am having trouble understanding how to configure it.

I have Google Auth Proxy running, and have configured it to pass upstream to Nginx, which then passes to a uWSGI socket serving my Django application. All of that works, but I don't know how to tell Django to accept the authenticated user that Google Auth Proxy passes. (Currently when I go to my site I am greeted by Google Auth Proxy, go through the Google authentication process, and am then forwarded to my Django project which presents the default Django admin login page.)

Google Auth Proxy runs on 127.0.0.1:4180 and forwards to 127.0.0.1:9090. My Nginx config looks like this:

```
server {
    listen        9090;

    location / {
        uwsgi_pass 127.0.0.1:9991;
        include /usr/local/etc/nginx/uwsgi_params;
    }

}

server {
    listen        80;
    server_name   mysite.com;

    location / {
        proxy_pass http://127.0.0.1:4180;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_connect_timeout 1;
        proxy_send_timeout 30;
        proxy_read_timeout 30;
    }
}
```

According to bitly's [introductory blog post](http://word.bitly.com/post/47548678256/google-auth-proxy), Google Auth Proxy will pass the authenticated user to the upstream application "as HTTP Basic Auth (with an empty value for the password), and in a HTTP Header as X-Forwarded-User for applications that need that context."

My understanding is that I cannot set an environment variable in Nginx, so Django's [Authentication using REMOTE_USER](https://docs.djangoproject.com/en/1.6/howto/auth-remote-user/) seems like it wouldn't work.

What's the best way to handle this?

**Comment by jehiah** [comment]
@akrf I'm going to close this based on the last comments, but please comment or re-open if you were not able to get this to work.
