### ISSUE TITLE
Option to disable HttpOnly on cookie?

### ISSUE THREAD

**Issue by tomtaylor** [bitly/google_auth_proxy#57]
I'd like to share a cookie between multiple services, some of which make cross domain requests using JS. Currently, HttpOnly is set to true when the cookie is set and cleared. It'd be great to provide an option to disable this. 

Instinctively, I'd set this using a `-cookie-httponly` flag, but there's already a `-cookie-https-only` flag. I'd be inclined to rename this to `-cookie-secure`, which I think would be closer to the expected naming, but it's a breaking change. 

I'm happy to submit a PR to do this, but I wanted to check your thoughts on renaming the https flag.

**Comment by tomtaylor** [comment]
I just went ahead and submitted the two things as separate PRs.

**Comment by jehiah** [comment]
closed by #58
