### ISSUE TITLE
Retrieve logged in users email

### ISSUE THREAD

**Issue by guzmo** [bitly/google_auth_proxy#75]
Is it possible to somehow get the logged in users email? If it is, how is this done?
We need to be able to identify the logged in user somehow.

**Comment by jehiah** [comment]
@guzmo are you using a current build? #73 added logging with the authenticated user so you should be able to do that based on access logs for the timeframe you have set for your cookies to expire.

**Comment by guzmo** [comment]
@jehiah Thanks for the super fast response :) 
This feels like alot of hax hehe I might do it to workaround it right now but will it be any other way in the future you think?

**Comment by jehiah** [comment]
Perhaps i'm miss understanding what you mean by "get the logged in users email". What are you trying to accomplish?

**Comment by ploxiln** [comment]
Perhaps you're looking for the `--pass-basic-auth` option, which adds headers to the passed-through requests which include the username and email? (it defaults on, you just need to make your application inspect the `X-Forwarded-Email` header)

**Comment by guzmo** [comment]
hehe I found this as well : ) thanks for all the help though! its nice to see that the repo is alive
