### ISSUE TITLE
Proxying Gate One

### ISSUE THREAD

**Issue by fvitorc** [bitly/google_auth_proxy#95]
I've successfully set up Nginx to proxy Gate One, a Web Terminal Emulator and SSH Client. But when I try to use google_auth_proxy with it, Gate One loads a page saying that is trying to connect to server, but it never does. I have no idea what the problem is, but maybe it is because Gate One uses WebSockets. Does google_auth_proxy have support for WebSockets?

**Comment by jehiah** [comment]
It unfortunately does not currently support WebSockets. see #14 and #64 for some attempts at adding that functionality.
